name: Test and Deploy

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12.4

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r webapp/requirements.txt

            - name: Run tests
              run: |
                  python -m unittest discover -s webapp/ -p "unit_test.py"

    deploy:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Fetch all branches
              run: git fetch origin

            - name: Checkout deployment branch
              run: git checkout deployment

            - name: Merge main into deployment
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git merge main --no-edit --no-ff

            - name: Push changes to deployment
              run: git push origin deployment
