name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r webapp/requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s webapp/ -p "unit_test.py"

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://weatherappcicd.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_0c85daab7bb4443ca11250bef33d17b5 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_b166b896754a4647a037272464518cf2 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: weatherappcicd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0c85daab7bb4443ca11250bef33d17b5 }}/weatherappcicd/weather-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pythom-weather-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_29f87205516a44b3810b2c375e3654b3 }}
          images: 'weatherappcicd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0c85daab7bb4443ca11250bef33d17b5 }}/weatherappcicd/weather-app:${{ github.sha }}'
